
POST http://localhost:3001/api/user/login
Content-Type: application/json 

{
    "username": "user1",
    "password": "password2020"
}

###
POST http://localhost:3001/api/user/login
Content-Type: application/json 

{
    "username": "superuser",
    "password": "superuserpassword2020"
}

###

GET http://localhost:3001/get
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDU4NzE5MDYsImV4cCI6MTYwNTg3NTUwNn0.bWvKtpEac7ovnb0zcwOtwJdP6Hec6vONG0TCWPJIARE

###
post http://localhost:3001/api/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDY4MjI2NTYsImV4cCI6MTYwNjgyNjI1Nn0.UwDJFfKNDQe1XUxhm-LzlGiLxF14mq42wkM9sytKxoA
   
{
     "newuser": {
        "name": "user7",
        "password": "password2020"
    }
}

###

GET http://localhost:3001/api/content/startgame
Content-Type : application/json

{
    "limit" : 15,
    "categories" : [],
    "difficulty": 3
}

###

GET http://localhost:3001/api/content/category
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDY4MjM0NDAsImV4cCI6MTYwNjgyNzA0MH0.wfI4eB5jp5bTFzGqwXS87rhOMZWf1tl7F1k3kmmPpwQ


###

POST http://localhost:3001/api/content/category
Content-Type: application/json 
Authorization: Bearer s

{
    "newCategoryName": "New Category 1/12"
}

###

GET http://localhost:3001/api/content/allScenarios
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiR2T3R4ZGo5dk5Qak1KdmxwWnBOYjd1Sk1NbzltMkEubFF2ZmdUUkJVRldZcVp1Ym5rL2lZTyIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDc0NDM0MjEsImV4cCI6MTYwNzQ4NjYyMX0.PXWk0vVdMFjUOxmnbzdYhzTzFtjf5yhKyQIaIWoxmQQ

{
    "limit" : 1,
    "categories" : []
}

###

POST http://localhost:3001/api/content/complete
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDczMjgxNDAsImV4cCI6MTYwNzM3MTM0MH0.IcCH9MxCLCjllZqMtk1uCUM-XaW_7-mVDDB8neT2jco

{
    "scenarioNameVar": "Is this ok?",
    "questionTypeVar": 1,
    "questionTextVar": "Is this ok? Like, do you think it is ok? Thonk so? Or no?",
    "pictureVar": "/../img/TinkeringThonking.png",
    "questionOption1Var": "Yes", 
    "questionOption2Var": "It is", 
    "questionOption3Var": "No...", 
    "questionOption4Var": "Indeed",
    "questionCorrect1Var": 1,
    "questionCorrect2Var": 1,
    "questionCorrect3Var": 0,
    "questionCorrect4Var": 1,
    "questionExplanationVar": "*Thonking* ... ... ... Yes, yes it seems.",
    "scenarioDifficultyVar": 1,
    "scenarioCategoryVar": [9]
}

###

GET http://localhost:3001/api/content/statistics
Content-Type : application/json

{
    "scenarioIdVar": 12
}

###
PUT http://localhost:3001/api/content/statistics
Content-Type : application/json

{
    "statisticsArrayVar":[{
        "id": 12,
        "statistic": 0
    },
    {
        "id": 12,
        "statistic": 1
    },
    {
        "id": 12,
        "statistic": 2
    },
    {
        "id": 11,
        "statistic": 0
    }
    ]
}

###

DELETE http://localhost:3001/api/user/delete 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIxIiwicGFzc3dvcmRoYXNoIjoiJDJiJDEyJGFTQ3FEU1hSL3pTY094NTFFYTNlTi5yekhKMENTNVVnRUM3cDZOTTJTLk1TdFd2RGF6eTYyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2MDczNDg1NjQsImV4cCI6MTYwNzM5MTc2NH0.sO6E9I3vfGVgWiDRSq3Cg6Z_COSs6yePEenyVgxELFs

{
    "name": "user7"
}

###

DELETE http://localhost:3001/api/content/scenario 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiR2T3R4ZGo5dk5Qak1KdmxwWnBOYjd1Sk1NbzltMkEubFF2ZmdUUkJVRldZcVp1Ym5rL2lZTyIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDc0NDM0MjEsImV4cCI6MTYwNzQ4NjYyMX0.PXWk0vVdMFjUOxmnbzdYhzTzFtjf5yhKyQIaIWoxmQQ

{
    "scenarioToDeleteVar": 13
}

###

DELETE http://localhost:3001/api/content/category 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiR2T3R4ZGo5dk5Qak1KdmxwWnBOYjd1Sk1NbzltMkEubFF2ZmdUUkJVRldZcVp1Ym5rL2lZTyIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDc0NDM0MjEsImV4cCI6MTYwNzQ4NjYyMX0.PXWk0vVdMFjUOxmnbzdYhzTzFtjf5yhKyQIaIWoxmQQ

{
    "categoryToDeleteVar": 10
}
