
POST http://localhost:3001/api/user/login
Content-Type: application/json 

{
    "username": "superuser",
    "password": "superuserpassword2020"
}

###

GET http://localhost:3001/get
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDU4NzE5MDYsImV4cCI6MTYwNTg3NTUwNn0.bWvKtpEac7ovnb0zcwOtwJdP6Hec6vONG0TCWPJIARE

###
post http://localhost:3001/api/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDY4MjI2NTYsImV4cCI6MTYwNjgyNjI1Nn0.UwDJFfKNDQe1XUxhm-LzlGiLxF14mq42wkM9sytKxoA
   
{
     "newuser": {
        "name": "user7",
        "password": "password2020"
    }
}

###

GET http://localhost:3001/api/content/startgame
Content-Type : application/json

{
    "limit" : 15,
    "categories" : [],
    "difficulty": 3
}

###

GET http://localhost:3001/api/content/category
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDY4MjM0NDAsImV4cCI6MTYwNjgyNzA0MH0.wfI4eB5jp5bTFzGqwXS87rhOMZWf1tl7F1k3kmmPpwQ


###

POST http://localhost:3001/api/content/category
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDY4MjUyMjIsImV4cCI6MTYwNjgyODgyMn0.8F3dH98xNZ8dlo2RPDlI-KCIIta-QimXmqwY6QpQebc

{
    "newCategoryName": "New Category 1/12"
}

###

GET http://localhost:3001/api/content/allScenarios
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDczMjgxNDAsImV4cCI6MTYwNzM3MTM0MH0.IcCH9MxCLCjllZqMtk1uCUM-XaW_7-mVDDB8neT2jco


{
    "limit" : 1,
    "categories" : []
}

###

POST http://localhost:3001/api/content/complete
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cGVydXNlciIsInBhc3N3b3JkaGFzaCI6IiQyYiQxMiQyTWcySzlzTzhwNE1KeGFEL1FpY0d1QkFDQzRzZTFOVUFTZFVkdTVTbzdXTTBKUld5TkhlZSIsInJvbGUiOiJzdXBlcnVzZXIiLCJpYXQiOjE2MDczMjgxNDAsImV4cCI6MTYwNzM3MTM0MH0.IcCH9MxCLCjllZqMtk1uCUM-XaW_7-mVDDB8neT2jco

{
    "scenarioNameVar": "How many Leningrads fit in Stalingrad?",
    "questionTypeVar": 1,
    "questionTextVar": "Have you ever visited Stalingrad? It would help in this. How many Leningrads fit to Stalingrad?",
    "pictureVar": "/../img/ponderingPerson.png",
    "questionOption1Var": "0", 
    "questionOption2Var": "1", 
    "questionOption3Var": "2", 
    "questionOption4Var": "3 or more",
    "questionCorrect1Var": 0,
    "questionCorrect2Var": 1,
    "questionCorrect3Var": 0,
    "questionCorrect4Var": 0,
    "questionExplanationVar": "Volgograd (prev. name Stalingrad) is 859,4 km^2, and St. Petersburg (prev. name Leningrad) is 1 439 km^2.",
    "scenarioDifficultyVar": 3,
    "scenarioCategoryVar": [7]
}